\set ON_ERROR_STOP on
\set schema 'dramatiq'
\set state 'state'
\set queue 'queue'
\set worker 'worker'
\set result 'result'

CREATE SCHEMA IF NOT EXISTS :"schema";

CREATE TYPE :"schema".:"state" AS ENUM (
  'queued',
  'consumed',
  'rejected'
);

CREATE TABLE :"schema".:"queue"(
  message_id uuid PRIMARY KEY,
  queue_name TEXT NOT NULL DEFAULT 'default',
  "state" :"schema".:"state",
  mtime TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  -- message as encoded by dramatiq.
  message JSONB,
  -- Monotonic enqueue counter, tie-breaker for FIFO ordering.
  position BIGINT GENERATED BY DEFAULT AS IDENTITY,
  -- Do not deliver before this timestamp. Implements delay/eta server-side.
  available_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  -- Worker owning the message while consumed. NULL once requeued.
  worker_id uuid,
  consumed_at TIMESTAMP WITH TIME ZONE
) WITHOUT OIDS;

-- Hot claim path: workers poll due messages per queue in FIFO order. The
-- partial predicate keeps the index tiny whatever the table size.
CREATE INDEX ON :"schema".:"queue"(queue_name, available_at, position)
  WHERE "state" = 'queued';

-- Index state and mtime together to speed up purge and recovery.
CREATE INDEX ON :"schema".:"queue"("state", mtime);

-- One row per live worker process. Rows with a stale heartbeat mark dead
-- workers whose consumed messages must be requeued.
CREATE TABLE :"schema".:"worker"(
  worker_id uuid PRIMARY KEY,
  heartbeat_at TIMESTAMP WITH TIME ZONE NOT NULL
) WITHOUT OIDS;

-- Actor results, decoupled from the queue so acknowledged messages can be
-- deleted from the hot table immediately.
CREATE TABLE :"schema".:"result"(
  message_id uuid PRIMARY KEY,
  "result" JSONB,
  expires_at TIMESTAMP WITH TIME ZONE
) WITHOUT OIDS;
